Review `views` in metacat DSL (#18)
## Context

Other frameworks (Cutlass, Mojo) abstract memory access using the concept of `Layout`, see here https://github.com/hellas-ai/wiki/pull/8 for details.

TLTR A `Layout` is a pair `shape` and `stride`. The `shape` tells us the dimension of an item while `stride` how it is mapped to linear physical memory.

### Design choices

#### `stride` is implicit (different from Mojo, Cutlass)
In our context, we have a similar abstraction, but different names
* `view` is a layout, we specify the `shape` but the `stride` is implicit.
* we informally refer to layout to indicate the stride, i.e. how it is linearized to physical memory. In the literature, this is typically called `stride`, even if I think our terminology is better.

Should we make the `stride` explicit in type? I don't know. What I am currently assuming is that a view is essentially a finite function `Fin (n, m) -> f32`. We assume that the `stride` is given when the function is defined, but it is not visible in kernel/user code. This is based similar to what @statusfailed proposed elsewhere.

Other frameworks use explicit strides for doing complex tiling operations. As explained here, https://github.com/hellas-ai/wiki/pull/8 layouts are not always injective/surjective and more complex patterns require to work with the stride. This makes code more complex. Do we need strides? Perhaps no at the moment.

#### Metacat DSL changes

We have high level operations to change the shape of memory/grid logical coordinates
* `gpu.view.linearize`: 2d -> 1d, 3d -> 1d
* `gpu.view.group`: 1d -> 2d
* `gpu.view.group-by-tile`: 4d -> 2d (from grid to tile)
* and others

We don't model stride here and for now we assume row major. Perhaps sufficient for our context, but I don't know if we can capture more complex behavior.

I changed `gpu.view.group`: it doesn't take `thread` and `block` as inputs, but a generic "linear" view. We don't use `thread.id` and `block.id` in kernel code because we don't want to have any index arithmetic here: instead we have `gpu.grid.view` to get the logical coordinates for the current worker running a kernel where how the coordinates are computed is transparent, we can use the same code for different grid shapes.

### Certified compiler

Currently, the compiler CUDA backend has some logic to add guards in order to guarantee safe access. In this PR we add the possibility to add a certificate to prove some properties of kernels.

```
cargo run -q -p catena-cli -- compile stdlib/core.hex stdlib/gpu.hex examples/fill-one-array.hex --emit cuda --theory data --entry user.f32.fill-one --proof stdlib/gpu.proof.hex examples/fill-one-array.proof.hex
```

* if you don't want proof checking, you have to explicitly opt out `--no-proof`
* we check only for safe access. It is very strict: if you cannot prove safety, the compiler aborts. We may relax this in the future, but it means that the compiler has to learn how to heal some unsafe programs (e.g. adding guards) or users have to change the kernel.
* This allows us to keep the compiler "thin". We removed logic for guards.

```
Error: no proof of gpu memory safety for `gpu.global.store view out_view for memory out`; expected proof `user.f32.fill-one.out.out_view.safe-access`
```

Limitations
* we look for theorems by name/conventions. This works because for now theorems are about single hyperedges. We may need more sophisticated approaches based on graph matching.

## What's next

LLMs can generate proofs in a feedback loop.